# Generated by Django 3.0.1 on 2020-01-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kabir_Singh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songs', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artists',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='comany',
            new_name='company',
        ),
    ]
