# Generated by Django 3.0.1 on 2020-01-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0002_auto_20200105_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kabir_Singh',
        ),
    ]
