# Generated by Django 3.0.1 on 2020-01-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0003_delete_kabir_singh'),
        ('Songs', '0002_kabir_singh_war'),
    ]

    operations = [
    ]
