# Generated by Django 3.0.1 on 2020-01-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0004_merge_20200107_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('artists', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Songs.Album')),
            ],
        ),
        migrations.DeleteModel(
            name='Kabir_Singh',
        ),
        migrations.DeleteModel(
            name='War',
        ),
    ]
