# Generated by Django 3.0.1 on 2020-01-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0005_auto_20200107_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='poster',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
