# Generated by Django 3.0.1 on 2020-01-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0006_song_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='video',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
