# Generated by Django 3.0.1 on 2020-01-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetails',
            name='root',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
