# Generated by Django 3.0.1 on 2020-01-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_moviedetails_root'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starcast',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='starcast',
            old_name='role_as',
            new_name='name2',
        ),
        migrations.RenameField(
            model_name='starcast',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='starcast',
            name='name3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='starcast',
            name='name4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='starcast',
            name='name5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='starcast',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='starcast',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='starcast',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='starcast',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='starcast',
            name='role_as1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='starcast',
            name='role_as2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='starcast',
            name='role_as3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='starcast',
            name='role_as4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='starcast',
            name='role_as5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
