# Generated by Django 3.0.1 on 2020-01-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_auto_20200116_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starcast',
            old_name='name1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='starcast',
            old_name='photo1',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='starcast',
            old_name='name2',
            new_name='role_as',
        ),
        migrations.RemoveField(
            model_name='starcast',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='starcast',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='starcast',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='starcast',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='starcast',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='starcast',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='starcast',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='starcast',
            name='role_as1',
        ),
        migrations.RemoveField(
            model_name='starcast',
            name='role_as2',
        ),
        migrations.RemoveField(
            model_name='starcast',
            name='role_as3',
        ),
        migrations.RemoveField(
            model_name='starcast',
            name='role_as4',
        ),
        migrations.RemoveField(
            model_name='starcast',
            name='role_as5',
        ),
    ]
