# Generated by Django 3.0.1 on 2020-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0005_movie_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='movie_users',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
