# Generated by Django 3.0.1 on 2020-01-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0007_showtime_talkies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='time',
            new_name='time1',
        ),
        migrations.AddField(
            model_name='showtime',
            name='time2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='time3',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
