# Generated by Django 3.0.1 on 2020-01-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0012_remove_dates_talk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='talk',
        ),
        migrations.AddField(
            model_name='showtime',
            name='talk',
            field=models.ManyToManyField(blank=True, null=True, to='Movie.Talkies'),
        ),
    ]
