# Generated by Django 3.0.1 on 2020-01-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0015_auto_20200126_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='time',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='time3',
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.TimeField(blank=True, null=True)),
                ('time2', models.TimeField(blank=True, null=True)),
                ('time3', models.TimeField(blank=True, null=True)),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.ShowTime')),
            ],
        ),
    ]
