# Generated by Django 3.0.1 on 2020-01-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0016_auto_20200126_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='show',
        ),
        migrations.AddField(
            model_name='time',
            name='talk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.Talkies'),
        ),
    ]
