# Generated by Django 3.0.1 on 2020-01-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0017_auto_20200126_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='price',
        ),
        migrations.AddField(
            model_name='time',
            name='price1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='price2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='price3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
