# Generated by Django 3.0.1 on 2020-01-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0018_auto_20200126_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
