# Generated by Django 3.0.1 on 2020-02-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0019_auto_20200128_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='talk',
            new_name='talkies',
        ),
    ]
