# Generated by Django 3.0.1 on 2020-02-05 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0020_auto_20200204_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='Rs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='Blank', max_length=100)),
                ('st', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.ShowTime')),
                ('talkies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.Talkies')),
            ],
        ),
    ]
