# Generated by Django 3.0.3 on 2020-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0025_auto_20200515_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
